services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: irene
      MONGO_INITDB_ROOT_PASSWORD: Obasi6220
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://irene:Obasi6220@mongo:27017/users?authSource=admin
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://irene:Obasi6220@mongo:27017/tasks?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://irene:Obasi6220@mongo:27017/notification?authSource=admin
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo_data:
